services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: file_processor
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dev123_admin
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
      - ./file-upload-service/seed_database.sh:/docker-entrypoint-initdb.d/seed_database.sh

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # API Port
      - "9001:9001"  # Console Port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: dev123_admin
    command: server /data --console-address ":9001"
    volumes:
      - ./volumes/minio-data:/data

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"  # NATS Core
      - "8222:8222"  # Monitoring UI
    volumes:
      - ./volumes/nats-data:/data
    command: "-js"  # Enable JetStream

    #   - ./infrastructure/nats-server/nats-server.conf:/etc/nats/nats-server.conf
    # command: "-c /etc/nats/nats-server.conf -js"

  websocket-server:
    container_name: websocket-server
    build:
      context: ./websocket-server
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped


# >>>> Ideally, this secrets would not be in the repo. They are only inclided here for demo purposes. <<<<
    