services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: file_app
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dev123_admin
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # API Port
      - "9001:9001"  # Console Port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: dev123_admin
    command: server /data --console-address ":9001"
    volumes:
      - ./volumes/minio-data:/data

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: dragonfly
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"  # Same port as Redis for compatibility
    # environment:
    #   - DFLY_user_default_username=admin
    #   - DFLY_user_default_password=dev123
    volumes:
      - ./volumes/dragonfly-data:/data
    # command: ["--requirepass", "dev123_admin"]

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"  # NATS Core
      - "8222:8222"  # Monitoring UI
    volumes:
      - ./volumes/nats-data:/data
    command: "-js"  # Enable JetStream