services:
  postgres:
    image: postgres:latest
    container_name: postgres
    # ports:
    #   - "5432:5432"
    environment:
      POSTGRES_DB: file_processor
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dev123_admin
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
      - ./file-upload-service/seed_database.sh:/docker-entrypoint-initdb.d/seed_database.sh

  minio:
    image: minio/minio
    container_name: minio
    ports:
      # - "9000:9000" # API Port
      - "9001:9001" # Console Port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: dev123_admin
    command: server /data --console-address ":9001"
    volumes:
      - ./volumes/minio-data:/data

  nats:
    image: nats:latest
    container_name: nats
    ports:
      # - "4222:4222" # NATS Core
      - "8222:8222" # Monitoring UI
    volumes:
      - ./volumes/nats-data:/data
    command: "-js" # Enable JetStream

    #   - ./infrastructure/nats-server/nats-server.conf:/etc/nats/nats-server.conf
    # command: "-c /etc/nats/nats-server.conf -js"

  websocket-server:
    container_name: websocket-server
    build:
      context: ./websocket-server
    # ports:
    #   - "0.0.0.0:8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

  file-upload-service:
    container_name: file-upload-service
    build:
      context: ./file-upload-service
    # ports:
    #   - "3002:3002"
    environment:
      - DATABASE_HOST='localhost'
      - DATABASE_PORT=5432
      - DATABASE_USER='admin'
      - DATABASE_PASSWORD='dev123_admin'
      - DATABASE_NAME='file_processor'

      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=dev123_admin
      - MINIO_STAGING_BUCKET = 'staging'
      - MINIO_PROCESSED_BUCKET = 'processed'

      - NATS_URL=nats://nats:4222
      - NATS_STAGED_SUBJECT = "file.upload.completed"
      - NATS_PROCESSED_SUBJECT = "file.processing.completed"

      - WEBSOCKET_URL=ws://websocket-server:8080/ws
    depends_on:
      - postgres
      - minio
      - nats
      - websocket-server

  file-processing-service:
    container_name: file-processing-service
    build:
      context: ./file-processing-service
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=dev123_admin
      - DATABASE_NAME=file_processor

      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_USE_SSL=false
      - MINIO_ACCESS_KEY=UpcdoQgnk5Z8liDwyaXp
      - MINIO_SECRET_KEY=N9WYPZlYUMroTdIsnZwlZQVFTI6pQ5pFi55kC9UD

      - MINIO_STAGING_BUCKET=staging
      - MINIO_PROCESSED_BUCKET=processed

      - NATS_SERVERS=nats://nats:4222
      - NATS_STAGED_SUBJECT=file.upload.completed
      - NATS_PROCESSED_SUBJECT=file.processing.completed

      - WEBSOCKET_URL=ws://websocket-server:8080/ws
    depends_on:
      - nats
      - minio
      - websocket-server

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    # ports:
    #   - "3000:3000"
    environment:
      - API_GATEWAY_URL=http://file-upload-service:3002
      - WEBSOCKET_URL=ws://websocket-server:8080/ws
    depends_on:
      - file-upload-service
      - file-processing-service
      - websocket-server
    
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "81:80"
    volumes:
      - ./infrastructure/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend

# >>>> Ideally, this secrets would not be in the repo. They are only inclided here for demo purposes. <<<<
